<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PkiMaster.Domain\PkiMaster.Domain.csproj" />
      <ProjectReference Include="..\PkiMaster.Dto\PkiMaster.Dto.csproj" />
    </ItemGroup>

</Project>
